Resolved production image digest issue

diff --git a/.github/workflows/master-pipeline.yml b/.github/workflows/master-pipeline.yml
--- a/.github/workflows/master-pipeline.yml
+++ b/.github/workflows/master-pipeline.yml
@@ -441,31 +441,27 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # pull and tag svelte frontend image
+      # pull and tag Svelte frontend image
       - name: Pull and Tag Svelte Frontend Image
         run: |
           docker pull osklot12/svelte-frontend:latest
           DIGEST=$(docker inspect osklot12/svelte-frontend:latest --format='{{index .RepoDigests 0}}')
           echo "Svelte Frontend Digest: $DIGEST"
-          docker tag osklot12/svelte-frontend:latest osklot12/svelte-frontend:stable
-          docker push osklot12/svelte-frontend:stable
-          echo "Svelte Frontend Digest: $DIGEST" >> $GITHUB_ENV
+          echo "FRONTEND_DIGEST=${DIGEST}" >> $GITHUB_ENV
 
-      # pull and tag spring backend image
+      # pull and tag Spring backend image
       - name: Pull and Tag Spring Backend Image
         run: |
           docker pull osklot12/spring-backend:latest
           DIGEST=$(docker inspect osklot12/spring-backend:latest --format='{{index .RepoDigests 0}}')
           echo "Spring Backend Digest: $DIGEST"
-          docker tag osklot12/spring-backend:latest osklot12/spring-backend:stable
-          docker push osklot12/spring-backend:stable
-          echo "Spring Backend Digest: $DIGEST" >> $GITHUB_ENV
+          echo "BACKEND_DIGEST=${DIGEST}" >> $GITHUB_ENV
 
       # output the digests
       - name: Output Image Digests
         run: |
-          echo "Frontend Image Digest: ${{ env.DIGEST }}"
-          echo "Backend Image Digest: ${{ env.DIGEST }}"
+          echo "Frontend Image Digest: ${{ env.FRONTEND_DIGEST }}"
+          echo "Backend Image Digest: ${{ env.BACKEND_DIGEST }}"
 
   # cleaning up test environment
   cleanup-test-environment:
@@ -570,22 +566,26 @@ jobs:
       # set backend image with digest
       - name: Update Backend Deployment with Digest
         run: |
-          BACKEND_IMAGE_DIGEST=$(docker inspect osklot12/spring-backend:latest --format='{{index .RepoDigests 0}}')
-          kubectl set image deployment/backend-deployment backend=$BACKEND_IMAGE_DIGEST --record
-          echo "Updated backend deployment with image: $BACKEND_IMAGE_DIGEST"
+          kubectl set image deployment/backend-deployment backend=${{ env.BACKEND_DIGEST }} --record
+          echo "Updated backend deployment with image: ${{ env.BACKEND_DIGEST }}"
 
       # set frontend image with digest
       - name: Update Frontend Deployment with Digest
         run: |
-          FRONTEND_IMAGE_DIGEST=$(docker inspect osklot12/svelte-frontend:latest --format='{{index .RepoDigests 0}}')
-          kubectl set image deployment/frontend-deployment frontend=$FRONTEND_IMAGE_DIGEST --record
-          echo "Updated frontend deployment with image: $FRONTEND_IMAGE_DIGEST"
+          kubectl set image deployment/frontend-deployment frontend=${{ env.FRONTEND_DIGEST }} --record
+          echo "Updated frontend deployment with image: ${{ env.FRONTEND_DIGEST }}"
 
-        # waiting for deployments to roll out
+      # waiting for deployments to roll out
       - name: Wait for Deployments to Roll Out
         run: |
           kubectl rollout status deployment/backend-deployment --timeout=300s
           kubectl rollout status deployment/frontend-deployment --timeout=300s
+
+      # deploying containers (in case manifest files are already applied)
+      - name: Deploying Containers
+        run: |
+          kubectl rollout restart deployment/frontend-deployment
+          kubectl rollout restart deployment/backend-deployment
 
       # verifying all pods are ready
       - name: Wait for All Pods to Be Ready
@@ -594,13 +594,27 @@ jobs:
           kubectl wait --for=condition=Ready pods -l app=frontend --timeout=300s
           kubectl wait --for=condition=Ready pods -l app=postgres --timeout=300s
 
-      # deploying containers (in case manifest files are already applied)
-      - name: Deploying Containers
+      # validate backend deployment image
+      - name: Validate Backend Deployment Image
         run: |
-          kubectl rollout restart deployment/frontend-deployment
-          kubectl rollout restart deployment/backend-deployment
+          BACKEND_IMAGE=$(kubectl get deployment backend-deployment -o=jsonpath='{.spec.template.spec.containers[0].image}')
+          echo "Backend Deployment Image: $BACKEND_IMAGE"
+          if [[ "$BACKEND_IMAGE" != *"${{ env.BACKEND_DIGEST }}"* ]]; then
+            echo "Backend image update failed!"
+            exit 1
+          fi
 
-      # outputting kubernetes resource status
+      # validate frontend deployment image
+      - name: Validate Frontend Deployment Image
+        run: |
+          FRONTEND_IMAGE=$(kubectl get deployment frontend-deployment -o=jsonpath='{.spec.template.spec.containers[0].image}')
+          echo "Frontend Deployment Image: $FRONTEND_IMAGE"
+          if [[ "$FRONTEND_IMAGE" != *"${{ env.FRONTEND_DIGEST }}"* ]]; then
+            echo "Frontend image update failed!"
+            exit 1
+          fi
+
+        # outputting kubernetes resource status
       - name: Output Kubernetes Status
         run: |
           kubectl get all
