Edited download of gitleaks

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -19,13 +19,21 @@ jobs:
         uses: actions/checkout@v3
 
       # Install Gitleaks
-      - name: Install Gitleaks
+      - name: Download and install gitleaks
         run: |
-          curl -sSLo gitleaks https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64
-          chmod +x gitleaks
-          sudo mv gitleaks /usr/local/bin/
+          cd /tmp
+          sudo wget -q \
+            "https://github.com/zricethezav/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" \
+            -O gitleaks.tar.gz || \
+            (echo "Error downloading gitleaks ${GITLEAKS_VERSION} tarball" && exit 1)
+          sudo tar -xvzf gitleaks.tar.gz || \
+            (echo "Error unarchiving gitleaks ${GITLEAKS_VERSION} tarball" && exit 1)
+          sudo mv gitleaks /usr/bin/. || \
+            (echo "Error moving gitleaks for /usr/bin" && exit 1)
+        shell: bash
+        env:
+          GITLEAKS_VERSION: "8.18.1"
 
-      # Run Gitleaks with redaction enabled
-      - name: Run Gitleaks with Redaction
-        run: |
-          gitleaks detect --source . --redact
+      - name: Run gitleaks
+        run: gitleaks -v detect --no-git ${{ secrets.GITHUB_TOKEN }} --source .
+        shell: bash
